FROM node:24-alpine

LABEL project=gardener_docs_dev

# Install required tools    
RUN apk add --no-cache bash git

COPY . .

RUN npm ci

RUN npm run post-processing-part-1
RUN npm run post-processing-part-2
RUN npm run post-processing-index

# Expose dev server port
EXPOSE 5173

CMD ["npx", "vitepress", "dev", "--host", "0.0.0.0"]
