import fs from 'fs';
import path from 'path';
import { read, write } from './lib/frontmatter.js';
import {
  classify,
  buildUpstreamUrl,
  renderBanner,
  bannerKind,
  injectBanner,
  splitLeadingBanner,
  stripLegacyGeneratedBanner,
} from './lib/banner.js';

function findMarkdownFiles(dir) {
  const results = [];

  function traverse(currentPath) {
    try {
      const entries = fs.readdirSync(currentPath, { withFileTypes: true });

      for (const entry of entries) {
        const fullPath = path.join(currentPath, entry.name);

        if (entry.isDirectory()) {
          traverse(fullPath);
        } else if (entry.name.endsWith('.md')) {
          results.push(fullPath);
        }
      }
    } catch (error) {
      console.error(`Error reading directory ${currentPath}:`, error.message);
    }
  }

  traverse(dir);
  return results;
}

function main() {
  const targetDir = process.argv[2];

  if (!targetDir) {
    console.error('Usage: node part-banner.js <directory>');
    process.exit(1);
  }

  if (!fs.existsSync(targetDir)) {
    console.error(`Directory does not exist: ${targetDir}`);
    process.exit(1);
  }

  try {
    const files = findMarkdownFiles(targetDir);

    let managed = 0;
    let local = 0;
    let skipped = 0;
    let written = 0;

    for (const file of files) {
      const { data, content } = read(file);
      const kind = classify(data, content, file);

      if (kind === 'skip') {
        skipped += 1;
        continue;
      }
      if (kind === 'managed') managed += 1;
      else local += 1;

      const url = kind === 'managed' && data.github_repo ? buildUpstreamUrl(data, file) : null;
      const banner = renderBanner(kind, { url, autoGenerated: data.auto_generated === true });

      const { banner: existingBanner, rest } = splitLeadingBanner(content.trimStart());
      let base = content;
      if (existingBanner !== null) {
        const existingKind = bannerKind(content);
        // LOCAL is compared by type only, not by text: a LOCAL file already
        // carrying a LOCAL banner is left untouched even if the banner wording
        // has since changed, so a wording tweak does not rewrite every local
        // file. MANAGED is compared by full text, because its wording carries
        // the upstream URL and the stub/index variant, which must stay current.
        if (existingKind === kind && kind === 'local') continue;
        if (existingBanner === banner) continue; // managed banner already up to date
        // Stale banner (wrong kind, or managed wording/url changed): strip it so
        // the correct banner can be injected.
        base = rest;
      } else {
        // A legacy GENERATED banner from before the type was dropped is no longer
        // recognized by splitLeadingBanner; strip it here so it is not left in the
        // body with a new MANAGED banner injected in front of it.
        base = stripLegacyGeneratedBanner(content);
      }

      const injected = injectBanner(base, banner);
      if (write(file, injected, data)) written += 1;
    }

    console.log(
      `Processed ${files.length} files (${managed} managed, ${local} local, ${skipped} skipped, ${written} written)`,
    );
  } catch (error) {
    console.error('Error:', error.message);
    process.exit(1);
  }
}

main();
