apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: prometheus-tls
  namespace: prometheus
  labels:
    app: prometheus
spec:
  commonName: prometheus
  dnsNames:
    - prometheus.prometheus.svc
    - prometheus.prometheus.svc.cluster.local
    - localhost
  secretName: prometheus-tls
  issuerRef:
    name: issuer-selfsigned
    namespace: certs
  renew: true
