apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: victorialogs-tls
  namespace: victoria-logs
  labels:
    app: victorialogs
spec:
  commonName: victoria-logs
  dnsNames:
    - victorialogs-victoria-logs-single-server.victoria-logs.svc
    - victorialogs-victoria-logs-single-server.victoria-logs.svc.cluster.local
    - localhost
  secretName: victorialogs-tls
  issuerRef:
    name: issuer-selfsigned
    namespace: certs
  renew: true
