#!/bin/bash

set -eu
echo "Running website build script"

getGitHubToken() {
  # Check if gardener-ci is available (in local setup)
  command -v gardener-ci >/dev/null && gardenci="true" || gardenci=""
  if [[ $gardenci == "true" ]]; then
    # Get a (round-robin) random technical GitHub user credentials
    technicalUser=$(gardener-ci config model_element --cfg-type github --cfg-name "${1}" --key credentials | sed -e "s/^GithubCredentials //" -e "s/'/\"/g")
    if [[ -n "${technicalUser}" ]]; then
      # get auth token and strip lead/trail quotes
      authToken=$(jq -r '.authToken' <<<"$technicalUser")
      echo "${authToken}"
    fi
  fi
}

websiteRepoPath=$(readlink -f ${GARDENER_WEBSITE_PATH})
website="${websiteRepoPath}/docs"
repoPath="$(readlink -f "$(dirname "${0}")/..")"
pushd "$repoPath"
# Moving hugo to repo for building
mv /hugo .
# Running docforge
GITHUB_OAUTH_TOKEN=$(getGitHubToken github_com) \
DOCFORGE_CONFIG=".docforge/config.yaml" \
docforge
# Building 404.js
./.ci/404.sh
# Running hugo
pushd hugo 
rm -rf "$website"
hugo --minify --destination "$website"
# Bypass Jekyll processing 
echo '' > "${website}/.nojekyll"
popd
# Remove hugo build
rm -rf hugo
popd
echo "Committing website changes"
pushd "$websiteRepoPath"
git add . -A
git commit -m 'Automatic build triggered by last commit [skip ci]' || true
