#!/usr/bin/env bash

SOURCE_PATH="$(readlink -f "$(dirname ${0})/..")"
GARDENER_VERSION_PATH="$SOURCE_PATH/gardenerVersion"

${ADD_DEPENDENCIES_CMD} \
    --component-dependencies \
    '{"name": "github.com/gardener/gardener", "version": "'$(cat $GARDENER_VERSION_PATH)'"}'

cp "${BASE_DEFINITION_PATH}" "${COMPONENT_DESCRIPTOR_PATH}"
