#!/bin/bash

if [[ $(uname) == 'Darwin' ]]; then
  READLINK_BIN="greadlink"
else
  READLINK_BIN="readlink"
fi

imageVersion=10.0.2

if [[ -z "${IMAGE}" ]]; then
  IMAGE=eu.gcr.io/gardener-project/gardener-website-generator:${imageVersion}
fi

while [[ "$#" -gt 0 ]]; do
  case $1 in
  --prod) prod=true ;;
  --build) build=true ;;
  *)
    echo "Unknown parameter passed: $1"
    exit 1
    ;;
  esac
  shift
done

scripts=$(${READLINK_BIN} -f $(dirname ${0}))
content=$(${READLINK_BIN} -f $(dirname ${0})/..)

if [[ -n ${WLS} ]]; then
  scripts=${scripts:4} # strip /mnt from path if in WLS as mounts in docker for windows work only for /c/ paths
  content=${content:4} # strip /mnt from path if in WLS as mounts in docker for windows work only for /c/ paths
fi

containerName="website-dev"

echo "stoping and removing existing containers"
docker stop ${containerName}
docker rm ${containerName}

echo "Content path: ${content}"

if [[ -n ${prod} ]]; then
  docker run -ti --rm --name $containerName -v $scripts:/scripts -v $content:/src -p 1313:1313/tcp -e WEBSITE_PROD=true $IMAGE /scripts/run-hugo
elif [[ -n ${build} ]]; then
  docker run -ti --rm --name $containerName -v $scripts:/scripts -v $content:/src -p 1313:1313/tcp $IMAGE /scripts/run-hugo
else
  docker run -ti --rm --name $containerName -v $scripts:/scripts -v $content:/src -p 1313:1313/tcp -e HUGO_WATCH=true $IMAGE /scripts/run-hugo
fi
