#!/bin/bash

set -e

for i in "$@"
do
case $i in
  -c=*|--container=*) 
    CONTAINER="${i#*=}"
    shift
    ;;
  *) echo "Unknown parameter passed: $i"; exit 1;;
esac
done
if [[ -z "${CONTAINER}" ]]; then
  echo "No container specified. Either use the --container=contianer-name-or-id option (-c==container-name-or-id), or $CONTAINER environment variable to specify it. The -c | --container option has priority."
  exit 1;
fi

docker ps -a | grep ${CONTAINER}
echo "stopping container ${CONTAINER}"
docker stop ${CONTAINER}
