apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: otel-collector
  namespace: kube-system
  labels:
    app: otel-collector
spec:
  commonName: client
  dnsNames:
    - otel-collector
  secretName: otel-collector-tls
  issuerRef:
    name: issuer-selfsigned
    namespace: certs
  renew: true
