---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shoot-metrics
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shoot-metrics-otel
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - endpoints
      - services
      - pods
      - nodes
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shoot-metrics-otel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: shoot-metrics-otel
subjects:
  - kind: ServiceAccount
    name: shoot-metrics
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gardener.cloud:monitoring:otel-shoot-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener.cloud:monitoring:prometheus-shoot
subjects:
  - kind: ServiceAccount
    name: shoot-metrics
    namespace: kube-system
