name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'post-processing/**'
      - 'package.json'
      - '.github/workflows/test.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: post-processing lib tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Enable corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 24

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test
